### ISSUE TITLE
Possible issue in general topology formulation

### ISSUE THREAD

**Issue by 1ozturkbe** [1ozturkbe/EGPAnet#2]
This has to do with the head loss constraint on line 76. 
```python
                        H_loss[i, j] == f[i, j] * L[i, j] * V[i, j] ** 2 / (2 * D[i, j] * g),
```
Since the diameter can go to zero if the connectivity is zero, but also the velocity can go to zero, there can be some ill-conditioning.

**Comment by alisaab** [comment]
@1ozturkbe  I tried to force the diameter to be larger than D_min for all [i,j], but it didn't work and is still giving the same error.

**Comment by 1ozturkbe** [comment]
The general topology formulation has been shelved for a while, so will bring this up again in the future.
